### ISSUE TITLE
[mobile] Fix buttons alignment on Review > SRS page

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#14]
Thanks @tbrams.. didn't notice that the buttons collapse in 2 rows as soon as you add enough cards...

![buttons](https://cloud.githubusercontent.com/assets/169391/21962991/a9c93440-db31-11e6-8667-ce5e989741b5.png)

I remember discussing this on Google Group earlier. We agree that it was not necessary to repeat "cards" in each button, but we may need to remove the text altogether and use just numbers.

Or maybe I can get away with just normal font weight, and reduced padding.

**Comment by fabd** [comment]
Fixed on **staging**.

Made buttons a bit smaller, and smaller still on iPhone 5 (320px).

**Comment by tbrams** [comment]
Can confirm it looks nice now on my Sony Xperia X Performance ^_^
