### ISSUE TITLE
It's "Érase una vez", not "ÉRase una vez".

### ISSUE THREAD

**Issue by andresangelini** [fabd/kanji-koohii#142]
Hi Fabrice! First time creating an issue, so I'm sorry if I've misunderstood the guide.

I'm trying to write "**Érase una vez**" as the Spanish keyword at the beginning of my story for **昔** (frame **1184**) . However, once I save the story, the page renders it as "**ÉRase una vez**" (second character turns into a capital letter). This doesn't happen when the keyword is placed anywhere else.

Thanks!

**Comment by fabd** [comment]
Thank you. That's definitely a small bug with the auto-formatting of stories. I'll look at it.

**Comment by andresangelini** [comment]
No problem. I know it's not a big deal but I'm glad I could help.

**Comment by fabd** [comment]
Also « Être ou ne pas être » (french for "to be or not to be") shows up incorrectly as: `êTre ou ne pas être.`

**Comment by fabd** [comment]
Non-english characters are recognised now.

A fix has been deployed to the live site, let me know if there are still issues.

Note that there is *minimal* autoformatting. It won't bother auto formatting, eg. `« être ou ne pas être »`. This requires skipping the first non-alphabetic / non-word characters and it creates more issues than it solves. The intention is simply to add basic punctuation to improve shared stories, where the user doesn't use any punctuation.

**Comment by andresangelini** [comment]
It works! You're awesome.
