### ISSUE TITLE
Spelling error for #2427 狸 should be "raccoon dog" 

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#145]
From mspertus on the forums:

> the keyword for 狸 (2427)  should be "raccoon dog" not "racoon dog". I have double-checked that it is correct in the RTK3 book, so looks like a (nitpicky) bug in the site.

## Tasks

- [ ] update rtk3 source file in case `kanjis`table script is rerun later
- [ ] update dev & live databases (not worth rerunning scripts)

**Comment by ukanuk** [comment]
Another change in keywords: Heisig's latest updates swap the keywords of 村 (221) and 町 (96). So now Koohii should set 村=village and 町=town by default. See all Heisig's listing of errata at https://nirc.nanzan-u.ac.jp/en/publications/miscellaneous-publications/remembering-the-kanji/, and for this particular change see his [Errata in the 6th edition, 3rd printing](https://nirc.nanzan-u.ac.jp/en/files/2018/11/RK1-6th-errata-in-3rd-printing-1.pdf).
