### ISSUE TITLE
[mobile] Dictionary pick, word displayed on top of the buttons (layout issue)

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#149]
From Yuta73 @ forums

> I'm adding the dict entries while SRSing. But this issue makes impossible to press any of the buttons. As a workaround, I rotate the phone forcing a refresh, but this is very annoying. I've taken screenshots, but couldn't find a way to insert them. I'm using Chrome for Android in portrait mode.

https://drive.google.com/file/d/1zbfP_LBQieSo7jutZALOKHKSHSEkwFbu/view?usp=drivesdk Before
https://drive.google.com/file/d/1EpHsIvOGKZz0ixes7gkufpbcRuNuz2yT/view?usp=drivesdk  Bug
https://drive.google.com/file/d/14DA-CYnzdNTcbiH9sbrB-uINN_oT519z/view?usp=drivesdk  Trying to press "Yes"
https://drive.google.com/file/d/1URZ6xV89UsPQdEDdMbQhqrpF3s2QDnUO/view?usp=drivesdk   After refresh

And

> the display on my Samsung S8 is problematic when I want to add a word. The selected word in the dictionary is floating on top of the buttons. I found a temporary trick : rotating the screen to horizontal and then back to vertical puts it where it should at the beginning.

Samsung S8 with Chrome browser?

![mogygv-t5y1kgjt6huoe7kwrrbr7vmophd59z8foogvvu44dv8olwlkss6dypatnmqoadupyb6iahfzzackk w1339-h1134](https://user-images.githubusercontent.com/169391/47214617-cd739e00-d39e-11e8-9b7c-6fd7e9ea302b.png)

**Comment by fabd** [comment]
The layout of the card switches from "no vocab" to "vocab" with a simple CSS class on the container. So I am puzzled as to why it would work. Somehow the flex based layout doesn't graphically refresh?

Or the css class is not set somehow, but that is handled by Vue which is fairly compatible.

Google Chrome dev tools (emulation) shows no issue.

**Comment by Yuta73** [comment]
Is it too hard to keep "vocab" class even after pressing "yes"?. To me, keeping current layout with or without dict picks is a plus. As some kanjis don't have common words, they are constantly changing size from card to card.

**Comment by fabd** [comment]
> If that's no possible, just make the card contents vertically scrollable in case it size it's bigger than the container. At least this way, we'll still be able to press the answer buttons.

It's already the case for long word definitions.

This is an issue with flex layout somehow not refreshing.

Keeping the layout the same throughout a review? Something to consider. But this isn't a solution for this issue. Did you try under different browsers?

**Comment by fabd** [comment]
There **is** an error actually, or rather a warning from Vue I can see in development:

> [Vue warn]: Duplicate keys detected: '1463040'. This may cause an update error.

It's a weird issue that I haven't found a reproducible scenario. It could potentially be behind the lack of layout update on your end. So I'm going to look more in it. I shrugged it off because it didn't seem to do anything, and I *do* in fact use Vue's `key` attribute afaik.

**Comment by Yuta73** [comment]
I have a Samsung A9. Maybe is Samsung related?.
I just tried Opera browser for Android and again same issue.
Keeping the layout would help me, as I only would have to rotate and counter rotate the screen once per review session.
Currently, I have to do it for every new starred dict entry.

**Comment by fabd** [comment]
You tried the full Opera right, not Opera mini? Opera Mini has a ton of unsupported features as can be seen on caniuse.com (just to get that out of the way).

**Comment by Yuta73** [comment]
I've tried both

**Comment by fabd** [comment]
**Note for self later**

Appears to bea Chrome bug? Or I don't understand flex enough.  Switching a property on and off also fixes layout in Chrome device toolbar.

The **fix** involves putting both kanji & example word in a conditional to force a re-render of the inner flashcard portion, so that flex resizes elements properly. To this end a dummy container is also added to make sure that Vue's "diff" tree does not skip elements between "has vocab" and "doesn't have vocab" layouts.
