### ISSUE TITLE
Fix Mixed Content requests

### ISSUE THREAD

**Issue by Betadel** [fabd/kanji-koohii#175]
Sometimes during a review, the site attempts to load something via unsecure HTTP, which is then blocked by Google Chrome due to Mixed Content concerns. Whenever this happens, I can't continue anymore unless I reload the page, which makes me lose a lot of the progress I had made during the review (since it seems each Kanji reviewed is not saved immediately as you go).

Here is an example of the error I see in the Chrome console whenever this happens:

Mixed Content: The page at 'https://kanji.koohii.com/review?type=untested#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://10.10.196.194:9090/mwg-internal/de5fs23hu73ds/plugin?target=Auth&reason=Auth&ClientID=2467328541&ttl=3600&url=aHR0cHM6Ly9rYW5qaS5rb29oaWkuY29tL3N0dWR5L2VkaXRzdG9yeT91Y3NfY29kZT0xOTk5OCZyZXZpZXdNb2RlPTEmcm5kPTE1ODc3NDkwNTYxOTY%3D&rnd=1587749056'. This request has been blocked; the content must be served over HTTPS.

**Comment by fabd** [comment]
Hya,

i have no idea what this url is. Could it be 8nitiated by an extension?

**Comment by fabd** [comment]
The IP address `10.10.196.194` is a local IP. Maybe a plugin in the browser on computers at work, or some misbehaving extension.
