### ISSUE TITLE
Improve Star / Copy / Report buttons (icons and tap target)

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#18]
The Vote / Copy / Report buttons on Study pages work better now due to the viewport set to 1:1 on mobile (ie. everything is a bit larger, and users don't need to zoom in).

Feedback from @rinre on previous forum:

_I agree with toby, they work much better on the staging site. I tried it out now, and I find hitting the star is easy, but when hitting “report” I tend to hit the star instead (1/3 times or so). Perhaps a tiny bit more spacing between the symbols would be enough to improve this?_

**Solutions**
- Increase the tap target and / or spacing
- Refresh the icons with FontAwesome or SVG, which also solves pixellated / blurrines on Hi-DPI screens

![koohii local-koohii_dev php-study-kanji-65 iphone 6 1](https://cloud.githubusercontent.com/assets/169391/21966265/d49e9540-db70-11e6-98f2-0295b74c3ea2.png)

**Comment by rinre** [comment]
sounds likie good improvements, thank you!

**Comment by fabd** [comment]
Bit boring design but I will consider this issue addressed for now.

* star / copy / report should have a larger touch area and easier to use
* should reduce reports when user meant to vote because the icons were too tiny and close together
* using FontAwesome so icons should look sharp on hi dpi screens

![staging koohii com-study-kanji-fond iphone 6](https://cloud.githubusercontent.com/assets/169391/22173732/dc93d3d2-dfcb-11e6-9dd4-f57377971125.png)

I still need to do extensive refactoring to VueJS components as the old JS code is horrible to maintain. #21
