### ISSUE TITLE
Unable to use the site on mobile (only recently)

### ISSUE THREAD

**Issue by Navodrome** [fabd/kanji-koohii#185]
every time I try to log in on mobile, it sends me back to the homepage without logging me in. works just fine on desktop however. tried loading the desktop site on mobile and tried changing passwords but neither worked. The sites worked just fine on mobile up until around last week

**Comment by fabd** [comment]
In case you're not the same person I replied to via email :+1: 
> Make sure your tablet or desktop browser saves the cookies, that's all i can think of. Some privacy features might be set too high? Cookies should always at least live for the session.

> Otherwise it works fine on ipad here, no other reports so i assume it’s related to the device / browser app.
