### ISSUE TITLE
Mismatch between standard and mobile menu

### ISSUE THREAD

**Issue by TimPatrick** [fabd/kanji-koohii#198]
When viewing the top-bar menu from a standard-sized web browser, the **Flashcards > Manage Flashcards** menu item browses to the `/manage` landing page, which is great.

When viewing the flyout menu from a mobile-sized presentation, the associated **Flashcards > Manage** menu item browses instead to the `/manage/addcustom` landing page. Please alter this flyout menu item so that it browses to `/manage`, just as the standard presentation does.

**Comment by fabd** [comment]
Good catch, thanks
