### ISSUE TITLE
Unable to Create Account

### ISSUE THREAD

**Issue by sheheryark** [fabd/kanji-koohii#245]
![image](https://user-images.githubusercontent.com/13309823/155140739-d235724c-37f1-4a55-8885-1ca6a68310b7.png)

I have added correct email address and "Tokyo" as an answer to the question but it throws error.

**Comment by fabd** [comment]
I'm sorry I didnt answer this back then. "Invalid request" shows up if the email was temporarily flagged on the StopForumSpam database.
