### ISSUE TITLE
Learned list clears itself

### ISSUE THREAD

**Issue by c4b3z0n** [fabd/kanji-koohii#251]
Hello, I've been using the restudy feature recently and I've noticed that at some point, the learned list clears itself. It may be at the time a day pases for the SRS.
Yesterday I was restudying some kanji, I had around 10 on Learned (as per the green box on the left), but didn't make the review.
Today, going into the study page for some of the kanji, in fact didn't show the green box on the left (as in no kanji in learned list). I had to go through each one and add it to the learned list and then make the review.
(I like to review the day after I relearn the kanji)

Though in the past I didn't use this feature much, recently I've been trying it out, and this happened to me at least three times.
Also, it would be nice to have access to the "review (re)learned" button from the restudy page, and maybe see in that list what is already included.

TBH, in the past I didn't use the feature as I tend to go Hard for cards I don't know. Recently, coming back from a hiatus, it was useful for marking stories to rewrite using "No".

**Comment by fabd** [comment]
Quick update: I can acknowledge the issue.

What happens is the Learned list is cleared after _any_ SRS review, which is probably not the intended design.

I can't fix this now and haven't had the time to think a better design -- but I will keep this open as I agree it would be beneficial to be able to resume your "Learned" list on the following day.

For now, keep in mind if you do a SRS review, it will clear the list. So as a temporary workaround, if you do your SRS review first for the day, then add kanji to the Learned list, then they should be there the next day. So I guess something like 1) review ffrom the Learned box ( sidebar ) if any from yesterday, 2) then do your other SRS reviews, then 3) work through more Restudy kanji.

**Comment by fabd** [comment]
Actually I'm not sure why it was implemented the way it is.

I guess what it should do is :  

- upon any SRS review ( HARD YES NO EASY ) -> clear the kanji from the Learned list
  - if you answer NO , then the kanji is no longer LEARNED, but still in the RESTUDY list
- leave the Learned list alone indefinitely, clear it only when the user clicks "Clear" in the sidebar

**Comment by fabd** [comment]
Hi @c4b3z0n 

I haven't wrote a blog post yet - but the site is updated.

The Restudy List page was redesigned, so it will match better the upcoming homepage/dashboard redesign.

You can "Review Learned Kanji" from the Restudy List, at any time.

Your learned list should remain indefinitely until you either succesfully SRS review these kanji - or you manually select "Clear learned list". So you should be able now always to Restudy one day, and Review Learned Kanji at any time later.

You will see the `LEARNED` tags in the Restudy List table.

If you'd like to suggest any further tweaks following this update - or if you find some minor issues - feel free to post them in this thread and I will create a new issue if it's warranted.

Thanks for reminding me about this page! I initially discarded it while working on the upcoming homepage/dashboard redesign - to reduce the scope. But as I looked into this issue, I realized there will be a prominent "Restudy" button on the new homepage - and so the Restudy List needed to be updated to match the dashboard.

Hope you like it and thanks for posting the issue!
