### ISSUE TITLE
Add a list of last viewed kanji on the Study page sidebar

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#275]
Related to #267 

A simple list from most to least recent visited kanji - shown in the sidebar.

Current mockup in FIGMA : 

![Study-LAST VISITED](https://user-images.githubusercontent.com/169391/198621931-1505bd14-50f5-4385-903b-77bfd0aac260.png)

**The main purpose** is to allow to easily go back to other kanji recently worked on, without having to go forward/backword one by one, or use the search box.

As a side benefit it can also give better context for users (eg. take a break from the computer, come back, and you can see "ah, I have been studying kanji 50,51,52 and I'm currently on 53").

**Comment by Shibodd** [comment]
I've used it in the past days and It's already really useful! The only thing that i don't like is the fact that it is missing the kanji character itself, which IMHO is more recognizable than both the keyword and frame number.

**Comment by fabd** [comment]
I've added the kanji now. I was trying to save space for the keyword but I guess it works. A little heavier visually but it's fine.
