### ISSUE TITLE
Progress chart: RTK 3 not recognized as finished

### ISSUE THREAD

**Issue by rinre** [fabd/kanji-koohii#28]
![screenshot_20170118-012852](https://cloud.githubusercontent.com/assets/25132907/22046114/ceaaa692-dd1e-11e6-9ba6-a75f07a4f861.png)
![screenshot_20170118-012909](https://cloud.githubusercontent.com/assets/25132907/22046119/d70c1dc0-dd1e-11e6-8904-2fcbcd53f49b.png)

As seen in the screenshots, RTK3 is not "recognized" as finished (like RTK1 is) although its progress bar is full.
Edit: (RTK 3 is the second bar from the bottom showing 965/965)

**Comment by fabd** [comment]
@rinre Not at home but I suspect it may have been broken since adding 6th edition due to using simple index compares. I'll see if I can find a simple enough solution for this.

**Comment by fabd** [comment]
Doh sorry forgot to tag NEXT item

**Comment by fabd** [comment]
Fixed for next update. Not spending too much time making it look fancy because this will change eventually if I implement "goals". But, it's working.

![rtk3-complete](https://cloud.githubusercontent.com/assets/169391/22792031/9fe7c662-eeeb-11e6-8f05-96a06da2f9fc.png)
