### ISSUE TITLE
Lesson 58

### ISSUE THREAD

**Issue by Vinickw** [fabd/kanji-koohii#295]
I noticed that when I'm using the old edition kanji sequence, in the progress chart there is lesson 58 with no kanji. It doesn't happen using the new edition sequence.
![image](https://user-images.githubusercontent.com/89015723/222152569-091f2eb1-6e0b-42e8-845b-d0618b0fafd8.png)

**Comment by fabd** [comment]
This is fixed now, thanks!

For Old Edition, you should see Lesson 58 with 23 characters index 3008-3030.
