### ISSUE TITLE
Keywords for 村 and 町 are swapped

### ISSUE THREAD

**Issue by peytontucker** [fabd/kanji-koohii#301]
I don't think this is intentional, although I could be wrong. Per the 6th edition of RTK1, index 221 is "village" (currently "town" on koohii) and index 96 is "town" (currently "village" on koohii).

**Comment by fabd** [comment]
Could you confirm or infirm if you have perhaps the updated 6th edition like @FranticRain

and if so, confirm if you also see the same thing as FranticRain in this photo https://github.com/fabd/kanji-koohii/issues/308#issuecomment-1499461003

I dont know how to act on this, but it would clarify things.

**Comment by fabd** [comment]
Update: yes town and village were swapped in 6th Edition errata - updating the site.

**Comment by peytontucker** [comment]
Yep, the front of my book says "6th edition, updated to include the 196 kanji approved in 2010 for general use".

I checked #308 and I can confirm that my book is the same as pictured.

I'm sorry you have to reconcile all of these editions - seems difficult!

**Comment by fabd** [comment]
Thanks Peyton the site was just updated, the most infamous of errata changes, town & village is finally fixed.

I also updated #145 fyi.

Unfortunately the Nanzan Institute doesnt seem to host the errata and RTK Sample PDFs anymore so I dont actually have the 6th edition errata. Just going by older issues here.

**Comment by fabd** [comment]
> I checked https://github.com/fabd/kanji-koohii/issues/308 and I can confirm that my book is the same as pictured.

> Yep, the front of my book says "6th edition, updated to include the 196 kanji approved in 2010 for general use".
> 
> I checked #308 and I can confirm that my book is the same as pictured.
> 
> I'm sorry you have to reconcile all of these editions - seems difficult!

Fr #308  the swap of 230 and 231 is annoying. This one hasnt been changed - for now.

**Comment by peytontucker** [comment]
> Thanks Peyton the site was just updated, the most infamous of errata changes, town & village is finally fixed.
> 
> I also updated #145 fyi.
> 
> Unfortunately the Nanzan Institute doesnt seem to host the errata and RTK Sample PDFs anymore so I dont actually have the 6th edition errata. Just going by older issues here.

[Try this link](http://web.archive.org/web/20230000000000*/http://nirc.nanzan-u.ac.jp/en/files/2012/12/RK1-cumulative-errata-pre-6th-edition.pdf). Not sure if this is exactly what you're looking for, but Wayback Machine seems to have this pdf cached quite a few times.

**Comment by peytontucker** [comment]
I got sucked in and decided to try to hunt this down.

After a bit of searching I dug up the following two pdfs:

[6th edition errata in 1st and 2nd printings](http://web.archive.org/web/20220107034033/https://nirc.nanzan-u.ac.jp/en/files/2015/03/RK1-6th-errata-in-1st-2nd-printings.pdf)
[
6th edition errata in 3rd printing](http://web.archive.org/web/20211213033221/https://nirc.nanzan-u.ac.jp/en/files/2018/11/RK1-6th-errata-in-3rd-printing-1.pdf)

Both found from links on [this page](http://web.archive.org/web/20220120004852/https://nirc.nanzan-u.ac.jp/en/publications/miscellaneous-publications/remembering-the-kanji/)

Hope this helps!

**Comment by FranticRain** [comment]
I had also noticed the town/village difference but hadn't followed up on that, given the existing issues.

Of note is that my version has a publisher's key of:
```
23 22 21 20 19 18     11 10 9 8 7 6 5
```
I would read this as a 5th printing, but can't be totally certain.

**Comment by fabd** [comment]
@peytontucker awesome thanks a lot!
