### ISSUE TITLE
Review Summary Multipage Bug

### ISSUE THREAD

**Issue by ilya112358** [fabd/kanji-koohii#304]
After a SRS session I get to the review page with the list of all reviewed kanji. If it is long, it spans several pages like in the image:
![image](https://user-images.githubusercontent.com/9436418/228947494-bbe2fe09-457a-4a32-9ff9-8e979525807e.png)

But if I press "2" or "Next" to go to the next page, I get a blank page:
![image](https://user-images.githubusercontent.com/9436418/228947331-c4f9c8ad-cdd3-4440-b221-50e220cb4502.png)

Windows,  Google Chrome 111.0.5563.147, cookies cleared.

**Comment by ilya112358** [comment]
Probably related to #277

**Comment by fabd** [comment]
Thanks for reminding me about this bug! Fix should be live soon.

**Comment by ilya112358** [comment]
I confirm, it is fixed now, I switch between pages and sort by different columns without problems.
