### ISSUE TITLE
Lesson progress bar does not look correctly on mobile

### ISSUE THREAD

**Issue by UncomprehendingGale** [fabd/kanji-koohii#306]
Lesson progress bar on chrome mobile doesn't appear at all, it is just dots
![Screenshot_2023-03-31-19-56-59-10_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/105124851/229183917-c9eab027-aa5c-4ce6-bdab-d4dc959a27aa.jpg)
My phone is a OnePlus 10 in case it matters

**Comment by fabd** [comment]
Hey @UncomprehendingGale I've just updated the live site with various "mobile friendly" improvements to the Lesson progress bars. The "All Lessons" page and the homepage Dashboard have also been optimized to fit better.

I don´t have the time to update the blog atm. But until then please keep me updated if the changes work well, and/or if something is still buggy.

I'm also interested if some elements are a little too big or small overall. I don't have a smartphone, so I'm eyeballing all of this on the preview in Google Chrome dev tools.

**Comment by fabd** [comment]
Here's what I'm seeign in my preview:

![localhost_index_dev php_progress(iPhone SE)](https://user-images.githubusercontent.com/169391/230633395-e9ae97b4-6cc0-4e0c-86ef-d84009f31bc7.png)


And Dashboard : 

![dasdhaboawrds](https://user-images.githubusercontent.com/169391/230633960-cc726324-0412-4097-8791-fdbf913399df.png)

**Comment by UncomprehendingGale** [comment]
Yes, it all looks correct, thanks a lot!

Maybe i'll take this chance to bother you about something else, the font on the percentage progress is uneven, even in your own screen we can see that the second 6 in "6.6%" is a bit smaller

**Comment by fabd** [comment]
> Maybe i'll take this chance to bother you about something else, the font on the percentage progress is uneven, even in your own screen we can see that the second 6 in "6.6%" is a bit smaller

Hah,... someone else mentioned this a while ago. Is it that noticable? Maybe it's more noticeable on a smartphone display with retina resolution? I guess I could change it, it was meant to make the fractional part stand out.

**Comment by fabd** [comment]
Closed by #309
