### ISSUE TITLE
末 and 昧 order swapped for 6th Edition

### ISSUE THREAD

**Issue by FranticRain** [fabd/kanji-koohii#308]
It looks like indexes 230 and 231 are swapped from the order that they are in the book.

| RTK Index | Koohii Index | Kanji |
|-----|-----|-----|
| 229 | 229 | 未 |
| 230 | 231 | 昧 |
| 231 | 230 | 末 |
| 232 | 232 | 沫 |

**Comment by fabd** [comment]
Besides it would make a lot of sense for Heisig to have 未 and 末 one after the other, for menmonic building purposes. As it says in RTK 6th edition (2014) "This character is best learned in connection with that of the previous frame."

**Comment by fabd** [comment]
Sigh please tell me it ain't so.... please tell me they didn't change the index once again?

**Comment by fabd** [comment]
Let's  hope this is the only change. Please let me know if you find others.

There is a reference spreadsheet you can find here with 5th and 6th editions (prior to updates then):

https://github.com/fabd/kanji-koohii/blob/master/src/data/datafiles/RTK%20Editions%20Compared.ods

**Comment by fabd** [comment]
I mean we could add another column in there, and have "6th edition (updated)" but I'll be honest unless there are significant changes I'm tempted to just leave it as is.

**Comment by FranticRain** [comment]
I'll keep going through and let you know if I run into anything else. Given the 6th vs 6th updated conversation, I don't think it's worth fussing over with *just* this difference. I'm going through the whole book again to check up on some things, so I should make my way through it over the next month or so. Will keep you updated of any other quirks I find.

**Comment by FranticRain** [comment]
Ran through all of volume 1 finally and couldn't find any other differences.
