### ISSUE TITLE
Stale link to RK1 Supplement kanji list PDF

### ISSUE THREAD

**Issue by hermi362** [fabd/kanji-koohii#319]
The links to the list of supplementary kanji, as they appear in the following two pages, are no longer valid. 

https://kanji.koohii.com/manage
https://kanji.koohii.com/manage/addcustom

The invalid URL is
http://nirc.nanzan-u.ac.jp/en/files/2012/12/RK1-Supplement.pdf

**Comment by Vinickw** [comment]
Maybe adding a WebArchive capture would be a good idea.
https://web.archive.org/web/20200227181804/http://nirc.nanzan-u.ac.jp/en/files/2012/12/RK1-Supplement.pdf

**Comment by fabd** [comment]
Thank you both!
