### ISSUE TITLE
Fix the loading bottleneck on iOS Safari (FontAwesome CDN?)

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#32]
On my iPad Air 2 there is often a really long lag, half a second or more, you can see the progress bar is at just 10% or so, and there is the loading spinner, and the page is blank! **Horrible delays on page load for staging on iOS Safari >_>  makes no sense. It loads just fine on desktop.** Safari even crashed once, what the hell is going on?

On staging Google Analytics is not enabled, so it's not that.

The page is blank, so it suggests it happens before the content, and before the YUI 2 / VueJS dependencies which are loaded later towards the end of the document.

I don't know how to pinpoint this on the handheld device. But it could be a good idea to cache FontAwesome anyway, so maybe we can use our own cache setting.

**Solutions**
- deliver FontAwesome font from the koohii server, see if it makes a difference
- figure out how to create a minimal build of FontAwesome with selected icons (we probably use less than 5% of all those icons!!) ... or just postpone this till we use SVG instead #16

**Comment by faneca** [comment]
For debugging, I recommend you do a search for `remote debugging ios safari` or similar. For example: http://stackoverflow.com/questions/11262236/ios-remote-debugging
Maybe you could also use a version of firebug lite (js) injected on the page.
I own no iOS devices, so I can't help further as I have no experience in this very topic. Good luck!

**Comment by fabd** [comment]
Try #44 first.

**Comment by fabd** [comment]
Happens with many sites on my iPad so I'll consider this a wontfix.
