### ISSUE TITLE
Unable to log in and password reset emails are not being sent

### ISSUE THREAD

**Issue by colemanOSU** [fabd/kanji-koohii#324]
All attempts to log in to Koohii are met with "Invalid username and/or password". Password-reset emails are never sent (yes, I checked the spam folder too!).

I tried creating a new account to check, and not only was I unable to log in to it, but password-reset emails were not sent for that account either.

**Comment by fabd** [comment]
Hmm yes it seems lately outgoing emails are blocked. It's a server issue.

The contact form works though, could you send an account recovery request message with your username. Please email from the mail associated with your account.

**Comment by colemanOSU** [comment]
Thank you. I already sent an email and was able to recover my account.
