### ISSUE TITLE
Graph on "main" shows incorrect number of flashcards in box "7+" 

### ISSUE THREAD

**Issue by KalvinLightning** [fabd/kanji-koohii#329]
Since around 2024-04-04 the graph on the /main site, which shows how many flashcards are in each box, jumped to around 90000 for the box "7+". There should be only around 1200 for me. 
The other numbers are correct and the total amount of flashcards are correct too. I can also review cards like usual. But the graph is difficult to read this way.

I am on mobile using the DuckDuckGo browser and I also tested it with the standard browser and there is the same issue. I have e/OS/ v1.18 and Android 12.

How it looks like:
![Screenshot_20240404-231700_DuckDuckGo](https://github.com/fabd/kanji-koohii/assets/139277399/2378575f-5fb4-44a7-a639-95180da8cd9b)

**Comment by fabd** [comment]
Could you tell me your username or send me a mail with your username? (cf. contact page). This will make it easier to investigate the bug,

**Comment by fabd** [comment]
Sorry for the long delay. Thanks again for reporting this, the fix is live.
