### ISSUE TITLE
Site down (403 error)?

### ISSUE THREAD

**Issue by joliss** [fabd/kanji-koohii#347]
https://kanji.koohii.com/ seems to be down for me, both logged in and in an anonymous tab. I'm getting a 403 error.

Update: Hm, it seems to work when proxied. I wonder if my IP range is in an exclusion list? Fabrice, I sent you my location and IP via email. The IP block might be intentional, so please feel free to just close this issue.

**Comment by fabd** [comment]
Okay. I don't think I have received your email, double check maybe with the email shown on the /contact page. There are a bunch of IP range blocks indeed, typically when I see a lot of spam/registering attempts from certain IPs, or weird things in the access logs. Those are typically the usual ranges in Russia. some eastern europe countries, but also a few in UK. Germany etc.
