### ISSUE TITLE
[mobile] Fix long keyword in Study > My Stories

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#4]
## Fix layout for long keyword

_Issue transferred from the Google Group, screenshot from Ernir._

- Stories content may eventually extend edge-to-edge on smaller screens
- Ensure the meta info (stars, public status, etc) collapses below the keyword so no overlap
- Make keyword wrap
- ... also clip the content (in case of a long string of kanji/kana that doesn't word wrap)
- Reduce keyword font size?

![add7p7ryhk4ik0llaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/169391/21961557/1afeea4e-db0d-11e6-8bbf-d82081c0d383.png)

**Comment by rinre** [comment]
For me personally, I don't care if I can see the whole "keyword" in "my stories" (as most of it is usually just examples of vocab/readings (In reviewing and studying I like that I can see them though)), so a cutoff would be fine (maybe with an option to click it to see the whole keyword?). Or if it extends to two-three lines without overlap of the star, like you describe, whichever is simpler to implement :)

**Comment by fabd** [comment]
Fixed by today's update (live).
