### ISSUE TITLE
Review Summary - Bad link to detailed flashcard list

### ISSUE THREAD

**Issue by faneca** [fabd/kanji-koohii#50]
The paragraph above the `Back` button has a broken link pointing to `http://kanji.koohii.com/review/flashcardlist`. Should link to `http://kanji.koohii.com/manage/flashcardlist` instead.

**Comment by fabd** [comment]
Fixed for next update.

Note that the button was reverted to default size (instead of .btn-gl) since it will run out of space quickly for example in free review ( Back ) ( Repeat Review ) fills 70% of the width already with larger buttons.
