### ISSUE TITLE
"review" section does not show info about "new" cards.

### ISSUE THREAD

**Issue by carcols** [fabd/kanji-koohii#56]
After studying and adding new cards, if I go to the home page, above the "review" button it says "no expired kanji". If I click, I get to the space-repetition site, and I see that I have N new cards.

Maybe this is the intended behavior, but I guess it would be useful to have also the count of new and restudy cards there.

**Comment by fabd** [comment]
Part of **Improve the Home screen** #7

Copying your suggestion there.

I will post mockups there to iterate over some ideas.
