### ISSUE TITLE
Improve the Restudy & Learned workflow

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#6]
It was recognized that the Restudy & Learned UX, currently seen in the sidebar on desktop, can be logically merged together for a more logical flow.

- User "Starts" a restudy session, taking them to the first failed card
- User adds one or more failed card, each time "Add to learned list" is clicked, user is taken to the next failed card
- User selects "Clear" to cancel the restudy session, or "Review" to proceed with the SRS. Either way, the whole list is cleared

To be updated. **Working on this!**

**Comment by fabd** [comment]
Working on **staging** now.

I think it's definitely better. Although as it gets closer to an interactive flow, it highlights other problems.

- When I move back and forth I get confused because there is no big visual change. The "Lesson 3" in large font is static from one kanji to another and that makes the top of the page appear relatively identical. Can be solved by removing it altogether as was discussed earlier.

- I think maybe "Learned 3 of 15" would be better than just "Learned 3" (15 being the total of failed cards)

- It's tempting to try and fit a ( + ) button inside the "Learned" box, to add the current kanji. Downside is it's less obvious that the current kanji is a failed card, as the "Add" button was kind of implicitly saying that. Workaround would be some kind of red flag somewhere to make visually clear the kanji's forgotten status. Guess I'll have to experiment with these.

![download](https://cloud.githubusercontent.com/assets/169391/21964177/5fd9e7ec-db47-11e6-9bec-f3162021e422.png)


**RELATED BUGFIX**
- Since I added "Hard" answer it was not removing those kanji from the Learned list. Although the kanji may not be remembered yet, it is cleared from the red pile, so it is removed from the Learned list after the Review session.

**Comment by wi-ki** [comment]
Two things I've noted so far. 
- With long stories,  you have to scroll down to search the button 'add to learned list'. For me it's not a big deal but if a user have a lot of big stories it may be.

- After you review some cards it's not clear that you have to click clear button in order to start again. Say you have 50 restudy card. You add 20 and start reviewing. When you finish it's not obvious that you have to click clear to see the other 30 restudy cards

**Comment by rinre** [comment]
I like it a lot! works just like you described it :+1: 
I agree that "Learned 3 of 15" would be even better. 
Also, I have no idea if it is complex for the coding, but if it would be possible that the "learned" bar dissapears sooner after you finish the reviews it sould be even better IMHO (the last days I always ended up clearing it myself at some point).

**Comment by fabd** [comment]
@rinre @wi-ki Yes I agree it is a bit confusing particularly because you can't see the remaining non-cleared items after a review. You _could_ go to the Study > Restudy page to pick the first failed one and continue but it's not intuititve.

I suppose for now I'll just clear the list when Review is started. Besides when the user knows that I don't think there's a use case for reviewing smaller batches of a long "Learned" list.

**Comment by fabd** [comment]
**Update on staging**

- clear the Learned list when reaching "Review summary", so this works whether review is completed or user ends a review early with the "End" button. This way, a Learned list is not lost if the user mistakenly starts review (in that case hitting "back" or closing the page would not reset the learned list)

- shows "Learned 3 of 15" instead of just "Learned 3" during Restudy session

I'll consider this issue fixed for now. And create more specific items in the future for the Restudy flow.

Trying to get the next update out, and then we'll see how this works for people.
