### ISSUE TITLE
Add Patreon as a way of support

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#62]
This is what I'm currently working on (Feb 2, 2017).

## Patreon

- [x] Research and setup the account
  - [x] Designed banner for the Patreon page
  - [x] Writing the About page
  - [x] Figure out starting goal(s)
- [x] Launch the page (write a post, update site with the new links)

## Koohii

- [x] Add a Patreon section to the `/about/support` page
  - Simplify the choice with Patreon / PayPal, by removing the PayPal recurring option
  - [x] Update PayPal with a PayPal.Me link
- [x] Update the footer
- ~~Create an include for the bottom of News posts? A very small banner (one line text) with a link to the support page and/or directly to the Patreon page~~

## Someday/Maybe

- [ ] Link a Twitter / Facebook to the Patreon page

**Comment by dieps** [comment]
Perhaps have monthly/quarterly donation goals that fund the hosting, maintenance, etc. of the website. 

You can share the info with users with a banner like Wikipedia. 
http://cdn.thewire.com/img/upload/2012/11/27/rendered/a8a702c2e0aed35de369c9360b92392f_623x246.jpg

**Comment by fabd** [comment]
Well I will go in the direction of plugging the Patreon page / donations more but raising donations with specific goals is not something I want to do.

While I don't have much expectations I think it's financially doable to reduce my work week by one day, so the goal is to support myself working on the website.

We'll see.

**Comment by fabd** [comment]
@dieps Ah I might have misunderstood your post now I see how Patreon goals work. So a Patreon goal is a milestone for a monthly amount being reached. So it makes sense putting the web hosting + SSL costs as a goal, so when the goal is reached that means the basic hosting costs are covered each month. This should be fairly easy to reach and a simple clear goal to get started :)
