### ISSUE TITLE
Sign-in screen "Keep Me Logged In"

### ISSUE THREAD

**Issue by mikeru2** [fabd/kanji-koohii#66]
There used to be a "keep me logged in" check box below the sign-in. Until I noticed and started using this, the site would become unresponsive during long kanji reviews and I'd lose part of my work. When I left the review -- which I could do only by using the "exit" button -- I'd find I was no longer logged in. Very annoying. Using "keep me logged in" fixed that. The new version of the sign-in doesn't have this (or I can't find it). I just got logged out during a long review for the first time on the new site. Can you restore "keep me logged in" or fix this some other way? (I'm using Chrome on a laptop if this is relevant.)

**Comment by fabd** [comment]
There is a checkbox labelled "Remember me" on the Sign In page. It should be only a cosmetic change but it's possible something else happened.

Can you make sure you check that when signing in again, and let me know if the issue persists.

**Comment by fabd** [comment]
I could also just remove it and make the cookie persist per default. It's not really necessary since you can simply Log out on a public PC / device which clears the cookie.

**Comment by fabd** [comment]
@mikeru2 Can you confirm you see the "Remember me" checkbox?

Also you may be talking about another issue. The signed in status is saved in a cookie. If you don't check "Remember me" (as of writing), that cookie is deleted when the *browser* session ends. That means closing all browser windows.

If you leave the page open and come back a few hours later, that is another thing. That is the "php session". The server basically loses track. We could create another issue for that although I think I increased the php session time to several hours. It used to be a problem but I haven't heard anything about it for a long time.

**Comment by fabd** [comment]
Well the "Remember me" option should work.

I am abandoning removing the checkbox or making it "remember" by default as it may not be a good idea. Can't make my mind anyway. If people bring this up I may reopen the issue later.

http://ux.stackexchange.com/questions/20924/why-isnt-the-remember-me-checkbox-in-login-forms-enabled-by-default

**Comment by mikeru2** [comment]
Sorry to be slow to reply. I realize this thread is now closed, but wanted to say thanks. I'm now using "remember me" and I'll let you know if the problem reoccurs.
