### ISSUE TITLE
Update screenshots on Learn More page

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#67]
Sigh.

**Comment by dieps** [comment]
You deserve a medal... がんばって！

**Comment by fabd** [comment]
Fixed for next update. Updated on **staging**.

Still need to summarize the documentation but it looks better.

**Comment by fabd** [comment]
Now I need a simple Markdown library that I could plug into the site , and then convert Help page to a .md file that I can put in the repo so it's easier to maintain and accept contributions, perhaps even translations.

if you know a good Markdown libary in php without much dependencies fire away! (ideally it lets me insert any custom html or just ignores it)
