### ISSUE TITLE
Display amount of characters left in real time when editing a story

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#73]
I love this design on dribbble.com's Profile page:

![dribbble - characters left](https://cloud.githubusercontent.com/assets/169391/22853780/33ef2a2a-f05f-11e6-8ee1-5405671ecd15.gif)

Create a **VueJS component** that displays the amount of characters left in an input field or textarea, in real time for better user experience.

This is a fun little thing to practice VueJS before creating more complex components.

If such a VueJS component for this already exists, please let me know!

**Comment by fabd** [comment]
Requirements in case someone would contribute the component (quick draft):

* Properties: max length (Number), input ref (a CSS selector could be `#id` or `.class-name` , etc. to use with document.querySelector())
* The "warning" threshold where it switches to red, can be hardcoded (ie. 20 chars)
* The component root element uses `display:inline-block` by default which  can be easily aligned (`text-align:right`).
* test with Japanese Input Method (IME), test on mobile

**Comment by fabd** [comment]
Requirements in case someone would contribute the component (quick draft):

* Submit via CodePen( preferably), here is a [simple Vue 2.x pen](http://codepen.io/fabd/pen/NddWjo) that can be forked
* Don't use Bootstrap. This is a tiny component that doesn't need dependencies.
* Properties: max length (Number), input ref (a CSS selector could be `#id` or `.class-name` , etc. to use with document.querySelector())
* The "warning" threshold where it switches to red, can be hardcoded (ie. 20 chars). Use a [class binding](https://vuejs.org/v2/guide/class-and-style.html#Binding-HTML-Classes) instead of a inline style binding, so that the color can be configured via CSS overrides.
* The component root element uses `display:inline-block` by default which  can be easily aligned (`text-align:right`).
* Test with Japanese Input Method (IME), test on mobile
* Use [X-Template](https://vuejs.org/v2/guide/components.html#X-Templates) syntax because I will move the code to a .vue file
* You can reach me easily [via Gitter](https://gitter.im/kanji-koohii/development)

**Comment by faneca** [comment]
Ok, there you go: http://codepen.io/faneca/pen/pRGzpG
This is my preliminary attempt. Feedback is more than welcome, as this is my first with vue.js

**Comment by fabd** [comment]
Thanks faneca! Looks good to me. :+1: 

Actually I haven't refactored the Study edit area with VueJS yet so I'll  probably bind a change event to the text area, but that is a necessity of my legacy code and the way you did it makes way more sense :)  (ie. using the story in the model rather than getting the length from the input via DOM).

It's a pretty small thing but I thought someone might enjoy it.

Indeed it makes sense to add it in a parent component. So eventually I will have a "EditStory" component, which can include the CharsLeft one with the textarea as you did.

I think it would be a fun little thing for me to add in as well, it was requested before after all. I need to get the Patreon out though, but I'll get back to it!

**Comment by faneca** [comment]
Glad to hear the code was of some use. I've been away from koohii for the last few weeks, but I'll make sure to check the results in the near future ;-).

IMHO the counter not updating while composing is not a big deal, UX wise, so don't sweat it.

As always, thanks for the great work you put into koohii.
