### ISSUE TITLE
Study page : "Add Card" and "Edit Card" buttons look too similar

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#76]
Feedback from Nick

> My problem is the following one. Sometime, when I learn a new Kanji, after writting my story, I forget to click to "Add card" button. I wonder why but perhaps it comes from the fact that **the "Add card" button and the "Edit card" button, look like too much together.**
> 
> A idea could be to modify the color of the button (keep green for edit and make it blue for "add card").

**Comment by fabd** [comment]
Fixed by making rhe "Add Card" a link style, and a different color.

**Comment by jonesmartins** [comment]
I also think you should make them two different colors. Adding a card might be more common than editing it, thus giving it a higher priority than just a link style.

**Comment by fabd** [comment]
Thank you @jonesmartins   I thought the link / button would add more differentiation than color.  Good point that Adding a Card is the more common option. I am switching the styles, and also using a "ghost button" style instead of a floating link. Should be up in a couple minutes.

**Comment by jonesmartins** [comment]
Much better now! The 'ghost button' style was a great addition. :)

**Comment by jonesmartins** [comment]
By the way, there's a little bug on the ghost button. When you press the Edit and then close the little window, it stays in the 'pressed' state and doesn't come back to normal. Like so:
![image](https://cloud.githubusercontent.com/assets/15959626/23226405/3246cf6c-f914-11e6-8d8a-9df2ea30c07e.png)
