### ISSUE TITLE
[mobile] Fix the Study > My Stories SORT links (broken layout)

### ISSUE THREAD

**Issue by fabd** [fabd/kanji-koohii#8]
Can't just fix layout, need to redesign the sort UX.

One solution would be to use a dropdown for the sorting index, taking much less space. Since sorting index is not something that needs to be changed a lot, a dropdown sounds good.

![kj89atfne1atwqvxh311fl 979ffi5cwfodzwq94xby5s fx7ks2267zwhv0yoppcif chh5lrrrpn4pc6cxvgod7xd7jfp1vba1leht1rf9dpvqbvqbvqbvacyav8frenvasmyz8iaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/169391/21961859/653e8922-db15-11e6-9856-921fccb46040.png)

**Comment by fabd** [comment]
**Updated on staging**

Barebones fix for this with a <select> dropdown, amde me realize this doesn't cut it for mobile experience : the dropdown is tiny and there is no good way afaik to style the dropdown to make rows larger for touch.

Thinking of using the [Element Select component](http://element.eleme.io/#/en-US/component/select). Although it has wayyy more features than I need and I have to keep in mind the total bundle size. So maybe have to look into other simpler SELECT components.

**Comment by fabd** [comment]
Someone let me user their phone today. The staging site seems to work pretty good !

I noticed the native SELECT is already handled by a native UX on the phone! It appeared as a large modal panel, with large radio buttons to pick the option.

**Hence, I might not improve the experience at all if I use a fancy Javascript based SELECT.**

The person told me they never see a desktop style dropdown on the SELECT unless it is not the native ones.

So I'm tempted to say that's functionally done (the code is pretty raw though, using oldschool JS, needs a debase/throttle function).

**Comment by rinre** [comment]
Good job, looks a lot better! The dropdown works great, like you yourself have seen. 
The only remaining problem is that (my) too long keywords don't fit on the mobile (on my desktop it's no problem). I guess it is no problem for most users, so I understand if it is not a priority, but If it would be possible to make the keyword take up two rows (it it's too long for one), that would be perfect :)

**Comment by fabd** [comment]
It's functionally done, so closing this.
